### ISSUE TITLE
Provide a list of StudyIds for a submission

### ISSUE THREAD

**Issue by rosibaj** [cancogen-virus-seq/muse#39]
will help to populate this on the ui for submitters.
![image](https://user-images.githubusercontent.com/15824252/115415502-f752e900-a1c4-11eb-819d-6a2967ce6ca0.png)

**Comment by jaserud** [comment]
StudyIds is available as an array. It will be empty for existing submissions though (since this was added as a new field/column in submission).

![image](https://user-images.githubusercontent.com/34698315/117151830-6e70ab80-ad87-11eb-92c7-88e4c071a489.png)

**Comment by rosibaj** [comment]
![image](https://user-images.githubusercontent.com/15824252/117185942-5e1cf880-ada8-11eb-8a1a-ab8539d664c2.png)
 Can see on Ui looks great! thank you @caravinci @jaserud !
