### ISSUE TITLE
BUG: double quotes prevent the TSV from being parsed

### ISSUE THREAD

**Issue by rosibaj** [cancogen-virus-seq/muse#85]
- The Data Curator was attempting to upload data for the AB group, and encountered an `Internal Server Error`
- @rosibaj requested logs and it showed the TSV --> JSON parser was breaking bc this character was not escaped. 

## Expected behaviour
the quote should not break TSV parsing

**Comment by andricDu** [comment]
@rosibaj is this good for release, do you need to test?
