### ISSUE TITLE
API: Concatenated Download 

### ISSUE THREAD

**Issue by rosibaj** [cancogen-virus-seq/muse#9]
- [ ] Take a list of analysis ids
- [ ] Concatenate the FASTA's to one file, which is exported.

**Comment by rosibaj** [comment]
@jaserud We have identified a bug. 

When i use the FASTA download with no active query, i get an empty file: 

![image](https://user-images.githubusercontent.com/15824252/115901635-70ee0f80-a42f-11eb-8bf2-aef30a16e831.png)

@jaserud moving back to in-progresss until this is addressed.

**Comment by akachru-github** [comment]
If you click download and have not made a row selection, what should we do?
- Right now, Select All is just for the current page. 
- Decision: 
  - **Under download pulldown menu, add new button for DOWNLOAD ALL. This is available all the time**
  - **If no rows selected , all selections other than the new DOWNLOAD ALL function will be disabled (greyed out). These only enable when a row(s) are selected**

**Comment by rosibaj** [comment]
Implementation cases are now covered by other tickets - The scope of this ticket is completed.  thank you @jaserud!
